# Generated by Django 4.1.1 on 2022-09-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='названия')),
                ('image', models.ImageField(upload_to='')),
                ('director', models.CharField(max_length=50, verbose_name='режиссер')),
                ('rating', models.FloatField(default=0, verbose_name='рейтинг')),
                ('duration', models.FloatField(null=True, verbose_name='длительность')),
            ],
            options={
                'verbose_name': 'фильм',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='main.films')),
            ],
        ),
    ]
